Search.setIndex({
    docnames: [
        "backend",
        "index",
        "installation",
        "introduction",
        "metadata",
        "partner",
        "product",
        "product_attribute",
        "product_category",
        "product_tag",
    ],
    filenames: [
        "backend.rst",
        "index.rst",
        "installation.rst",
        "introduction.rst",
        "metadata.rst",
        "partner.rst",
        "product.rst",
        "product_attribute.rst",
        "product_category.rst",
        "product_tag.rst",
    ],
    titles: [
        "Backend Overview",
        "Welcome to Odoo Woocommerce Connector\u2019s documentation!",
        "Installation",
        "Introduction",
        "Sync MetaData",
        "Partner Management",
        "Product",
        "Product Attributes",
        "Product Categories",
        "Product Tags",
    ],
    terms: {
        In: [0, 2, 4, 5, 6, 7, 8, 9],
        thi: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        section: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        we: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        provid: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        an: [0, 2, 3, 6],
        basic: [0, 2],
        odoo: [0, 2, 4, 5, 6, 7, 8, 9],
        woocommerc: [0, 2, 4, 5, 6, 7, 8, 9],
        connector: [0, 2, 4, 5, 6, 7, 8, 9],
        along: 0,
        inform: [0, 3, 4, 5, 7],
        imag: [0, 6],
        help: [0, 3, 7, 8],
        you: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        understand: [0, 3, 5],
        structur: [0, 8, 9],
        compon: 0,
        consist: [0, 3, 4, 6, 7, 8, 9],
        sever: [0, 6],
        kei: [0, 4, 8],
        server: 0,
        i: [0, 1, 2, 3, 4, 5, 6, 7, 8],
        core: 0,
        integr: [0, 3, 4, 6],
        It: [0, 3, 4, 5, 6],
        manag: [0, 3, 6, 7, 8, 9],
        "": [0, 2, 3, 4, 5, 6, 7, 8],
        data: [0, 3, 4],
        busi: [0, 3, 6, 9],
        logic: 0,
        platform: [0, 3, 4],
        e: [0, 3],
        commerc: [0, 3],
        where: [0, 2, 5],
        your: [0, 2, 3, 4, 6, 7, 8, 9],
        onlin: [0, 4],
        store: [0, 4, 6, 7],
        oper: [0, 3, 5],
        engin: 0,
        act: 0,
        bridg: 0,
        between: [0, 3, 4, 8],
        facilit: 0,
        synchron: [0, 3, 4, 7, 8],
        commun: [0, 3],
        exchang: 0,
        mechan: 0,
        allow: [0, 6, 7],
        real: [0, 3],
        time: [0, 3, 6, 8],
        transfer: 0,
        ensur: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        autom: [0, 3],
        process: [0, 2, 3, 4],
        includ: [0, 4, 5],
        reduc: [0, 3],
        manual: [0, 3, 8],
        effort: [0, 8],
        streamlin: [0, 3, 4, 6, 8],
        user: 0,
        interfac: 0,
        can: [0, 2, 3, 4, 6, 7, 8, 9],
        access: [0, 2, 6],
        set: [0, 4, 6, 8],
        function: [0, 4, 5, 6, 7, 8, 9],
        perform: [0, 3, 4, 5, 6, 7, 8, 9],
        follow: [0, 2, 4, 6, 7, 8, 9],
        action: [0, 4, 5, 6, 7, 8, 9],
        sync: [0, 3],
        meta: 0,
        countri: [0, 4],
        state: [0, 4],
        tax: [0, 4],
        polici: [0, 4],
        ship: [0, 4],
        method: [0, 4],
        import: [0, 4],
        partner: [0, 1, 4],
        attribut: [0, 5, 6],
        valu: [0, 6, 7],
        categori: [0, 6],
        tag: [0, 6, 7],
        order: [0, 3, 4],
        To: [0, 3],
        effect: [0, 3, 6],
        need: [0, 2, 3, 6, 8, 9],
        credenti: [0, 2],
        consum: 0,
        ck: 0,
        requir: [0, 7],
        secur: 0,
        secret: 0,
        c: 0,
        anoth: 0,
        crucial: [0, 4, 9],
        locat: [0, 5],
        base: 0,
        url: [0, 6],
        smooth: 0,
        fine: 0,
        tune: 0,
        paramet: 0,
        meet: [0, 6, 9],
        specif: [0, 3, 4, 6, 7, 9],
        up: [0, 3, 4, 8],
        record: [0, 3, 5],
        limit: 0,
        custom: [0, 3, 7, 8, 9],
        By: [0, 3, 4, 7, 8],
        switch: 0,
        from: [0, 2, 3, 4, 5, 6, 7, 8, 9],
        test: [0, 5, 6, 7, 8, 9],
        mang: 0,
        our: [0, 3],
        stage: 0,
        level: [0, 7],
        flawlessli: 0,
        delv: [0, 6, 7, 8],
        go: [0, 2],
        through: [0, 3],
        each: [0, 3, 6, 7, 8],
        detail: [0, 2, 4, 5, 6, 7, 8, 9],
        instruct: [0, 2, 4, 5, 6, 7, 8, 9],
        offici: [1, 3],
        introduct: 1,
        instal: [1, 3],
        backend: [1, 2],
        metadata: 1,
        product_attribut: 1,
        product_categori: 1,
        product_tag: 1,
        product: [1, 3, 5],
        how: [2, 3, 4, 5, 8],
        app: 2,
        instanc: [2, 4, 6, 8],
        befor: [2, 3],
        begin: 2,
        make: [2, 3, 6, 7, 8],
        sure: 2,
        have: [2, 3, 7, 8],
        place: 2,
        should: 2,
        want: [2, 8],
        admin: 2,
        administr: 2,
        internet: 2,
        connect: [2, 3],
        ha: 2,
        activ: 2,
        log: 2,
        us: [2, 3, 4, 5, 6, 7, 8],
        navig: [2, 3],
        modul: [2, 3],
        dashboard: 2,
        search: 2,
        bar: 2,
        look: 2,
        when: [2, 4, 5, 6, 7, 8, 9],
        find: [2, 7, 8, 9],
        click: [2, 4, 5, 6, 7, 8, 9],
        view: 2,
        Then: 2,
        button: [2, 5],
        start: 2,
        wait: 2,
        download: 2,
        mai: 2,
        take: 2,
        few: 2,
        moment: 2,
        depend: 2,
        devic: 2,
        speed: [2, 3],
        That: 2,
        The: [2, 3, 4],
        now: 2,
        readi: 2,
        configur: [2, 3, 4, 9],
        after: [2, 6],
        proce: 2,
        overview: 2,
        document: [2, 3],
        get: 2,
        idea: 2,
        about: 2,
        welcom: 3,
        depth: 3,
        guid: 3,
        its: [3, 6, 7, 8, 9],
        system: 3,
        seamlessli: [3, 6],
        power: [3, 8],
        solut: 3,
        versatil: 3,
        open: 3,
        sourc: 3,
        erp: 3,
        popular: 3,
        With: 3,
        more: 3,
        updat: [3, 7],
        enjoi: 3,
        both: [3, 4, 5],
        routin: 3,
        task: 3,
        entri: 3,
        tailor: 3,
        high: 3,
        handl: [3, 5, 6],
        heavi: 3,
        load: 3,
        without: [3, 6],
        break: 3,
        sweat: 3,
        background: 3,
        magic: 3,
        keep: 3,
        date: [3, 4, 6],
        ani: [3, 6],
        interrupt: 3,
        everyth: 3,
        independ: 3,
        assur: 3,
        A: [3, 8],
        hiccup: 3,
        one: 3,
        won: 3,
        t: [3, 6],
        hold: 3,
        back: 3,
        rest: 3,
        treat: 3,
        left: 3,
        behind: 3,
        stabil: 3,
        experi: [3, 9],
        fast: 3,
        robust: 3,
        like: 3,
        never: 3,
        reliabl: 3,
        count: 3,
        On: 3,
        resili: 3,
        minor: 3,
        issu: 3,
        impact: [3, 4],
        overal: 3,
        stai: 3,
        ahead: 3,
        curv: 3,
        while: [3, 5],
        other: 3,
        struggl: 3,
        ll: 3,
        superior: 3,
        technologi: 3,
        boost: 3,
        effici: [3, 9],
        faster: 3,
        fewer: 3,
        disrupt: 3,
        watch: 3,
        soar: 3,
        next: 3,
        gen: 3,
        Be: 3,
        part: 3,
        futur: 3,
        advanc: [3, 4],
        techniqu: 3,
        design: [3, 4, 8],
        modern: 3,
        peac: 3,
        mind: 3,
        easi: 3,
        know: 3,
        best: 3,
        hand: 3,
        join: 3,
        elit: 3,
        stand: 3,
        out: 3,
        competit: 3,
        built: 3,
        excel: 3,
        refer: 3,
        initi: 3,
        setup: 3,
        note: [3, 7, 8, 9],
        cover: 3,
        variou: 3,
        aspect: 3,
        troubleshoot: 3,
        tabl: 3,
        content: 3,
        differ: [3, 5, 6, 7, 8, 9],
        topic: 3,
        hope: 3,
        most: 3,
        If: [3, 5, 6, 8, 9],
        question: 3,
        assist: 3,
        pleas: 3,
        contact: 3,
        end: 3,
        comprehens: [3, 5],
        work: [3, 4, 5, 6, 7, 8, 9],
        For: 3,
        latest: 3,
        releas: 3,
        discuss: 3,
        visit: 3,
        websit: 3,
        forum: 3,
        support: 3,
        inquiri: 3,
        dedic: 3,
        team: 3,
        thank: 3,
        choos: 3,
        re: 3,
        here: [3, 5, 8],
        succe: 3,
        explor: [4, 5, 6, 7, 8, 9],
        featur: [4, 6, 8],
        simplifi: [4, 6, 8],
        essenti: [4, 5, 9],
        plai: [4, 6],
        vital: 4,
        role: [4, 6, 9],
        maintain: 4,
        accuraci: 4,
        retriev: 4,
        particularli: [4, 8],
        fulfil: 4,
        address: [4, 5],
        ar: [4, 5, 6, 7, 8, 9],
        behavior: [4, 5],
        also: [4, 6, 7],
        contain: 4,
        accur: 4,
        calcul: 4,
        across: 4,
        cost: 4,
        enabl: [4, 7],
        seamless: 4,
        critic: 4,
        upcom: [4, 5, 6, 7, 8, 9],
        instac: 5,
        There: [5, 6, 7],
        which: [5, 7],
        could: 5,
        possibl: 5,
        scenario: 5,
        approach: [5, 7],
        all: [5, 7],
        relev: 5,
        captur: 5,
        focus: 5,
        similar: [5, 8],
        previou: 5,
        involv: 5,
        uniqu: [5, 7],
        identif: 5,
        avail: [5, 7],
        fals: [5, 6],
        rais: 5,
        map: 5,
        error: 5,
        successfulli: 5,
        true: 5,
        case: [6, 7, 8, 9],
        sku: 6,
        even: 6,
        lack: 6,
        boolean: 6,
        doesn: 6,
        default: 6,
        type: 6,
        defin: [6, 7],
        save: [6, 8],
        automat: 6,
        categor: [6, 8, 9],
        new: 6,
        specifi: 6,
        similarli: 6,
        onli: 6,
        creat: [6, 7, 9],
        modifi: 6,
        pivot: 6,
        primari: 6,
        entir: 6,
        catalog: [6, 7, 8, 9],
        ad: 6,
        Their: 6,
        associ: [6, 7],
        them: [6, 7, 8],
        rich: 6,
        organ: [6, 8, 9],
        match: [6, 8],
        woo: 6,
        exist: [6, 9],
        link: [6, 9],
        togeth: 6,
        correctli: 6,
        auto: 6,
        visual: 6,
        appeal: 6,
        galleri: 6,
        addit: 6,
        displai: 6,
        relat: [6, 7, 8, 9],
        insight: [6, 7, 8],
        environ: 7,
        characterist: 7,
        variat: 7,
        size: 7,
        color: 7,
        materi: 7,
        often: 7,
        repres: 7,
        option: 7,
        These: 7,
        precis: 7,
        call: 7,
        eventu: 7,
        list: [7, 8, 9],
        menu: [7, 8, 9],
        two: 7,
        wai: 7,
        suitabl: 7,
        appli: 7,
        wide: 7,
        rang: 7,
        altern: 7,
        individu: 7,
        ideal: 7,
        certain: 7,
        gener: 7,
        easier: 8,
        brows: [8, 9],
        what: 8,
        thei: 8,
        abil: 8,
        alreadi: [8, 9],
        check: 8,
        same: [8, 9],
        name: [8, 9],
        found: 8,
        linkag: 8,
        remain: 8,
        per: 8,
        prefer: 8,
        avoid: 8,
        serv: 9,
        duplic: 9,
        instead: 9,
        prevent: 9,
    },
    objects: {},
    objtypes: {},
    objnames: {},
    titleterms: {
        backend: [0, 5],
        overview: 0,
        The: [0, 6, 7, 8, 9],
        architectur: 0,
        gener: 0,
        view: 0,
        advanc: [0, 5, 6],
        configur: [0, 5, 6],
        product: [0, 6, 7, 8, 9],
        mode: 0,
        next: [0, 2, 4, 5, 7, 8, 9],
        step: [0, 2, 4, 5, 7, 8, 9],
        welcom: 1,
        odoo: [1, 3],
        woocommerc: [1, 3],
        connector: [1, 3],
        "": 1,
        document: 1,
        instal: 2,
        prerequisit: 2,
        introduct: 3,
        about: 3,
        kei: 3,
        featur: 3,
        get: 3,
        start: 3,
        sync: 4,
        metadata: 4,
        understand: 4,
        button: [4, 6, 7, 8, 9],
        partner: 5,
        manag: 5,
        custom: 5,
        import: [5, 6, 7, 8, 9],
        case: 5,
        1: 5,
        creat: 5,
        main: 5,
        bill: 5,
        ship: 5,
        2: 5,
        3: 5,
        4: 5,
        onli: 5,
        set: 5,
        email: 5,
        5: 5,
        first: 5,
        name: 5,
        6: 5,
        last: 5,
        7: 5,
        8: 5,
        usernam: 5,
        9: 5,
        boolean: 5,
        field: 5,
        allow: 5,
        without: 5,
        tab: 5,
        attribut: 7,
        categori: 8,
        link: 8,
        exist: 8,
        tag: 9,
    },
    envversion: {
        "sphinx.domains.c": 3,
        "sphinx.domains.changeset": 1,
        "sphinx.domains.citation": 1,
        "sphinx.domains.cpp": 9,
        "sphinx.domains.index": 1,
        "sphinx.domains.javascript": 3,
        "sphinx.domains.math": 2,
        "sphinx.domains.python": 4,
        "sphinx.domains.rst": 2,
        "sphinx.domains.std": 2,
        sphinx: 60,
    },
    alltitles: {
        "Backend Overview": [[0, "backend-overview"]],
        "The Backend Architecture": [[0, "the-backend-architecture"]],
        "General Backend View": [[0, "general-backend-view"]],
        "Advance Configuration Backend View": [
            [0, "advance-configuration-backend-view"],
        ],
        "Production Mode": [[0, "production-mode"]],
        "Next Steps": [
            [0, "next-steps"],
            [4, "next-steps"],
            [5, "next-steps"],
            [7, "next-steps"],
            [2, "next-steps"],
            [8, "next-steps"],
            [9, "next-steps"],
        ],
        "Sync MetaData": [[4, "sync-metadata"]],
        "Understanding the SYNC METADATA Button": [
            [4, "understanding-the-sync-metadata-button"],
        ],
        "Partner Management": [[5, "partner-management"]],
        "Customer Import": [[5, "customer-import"]],
        "Case 1: Create Customer with Main Customer, Billing, and Shipping": [
            [5, "case-1-create-customer-with-main-customer-billing-and-shipping"],
        ],
        "Case 2: Create Customer with Main Customer and Billing Customer": [
            [5, "case-2-create-customer-with-main-customer-and-billing-customer"],
        ],
        "Case 3: Create Customer with Main Customer and Shipping Customer": [
            [5, "case-3-create-customer-with-main-customer-and-shipping-customer"],
        ],
        "Case 4: Create Customer with Main Customer and Only Set Email": [
            [5, "case-4-create-customer-with-main-customer-and-only-set-email"],
        ],
        "Case 5: Create Customer with Main Customer and Set Email and First Name": [
            [
                5,
                "case-5-create-customer-with-main-customer-and-set-email-and-first-name",
            ],
        ],
        "Case 6: Create Customer with Main Customer and Set Email and Last Name": [
            [
                5,
                "case-6-create-customer-with-main-customer-and-set-email-and-last-name",
            ],
        ],
        "Case 7: Create Customer with Main Customer and Set Email, First Name, and Last Name":
            [
                [
                    5,
                    "case-7-create-customer-with-main-customer-and-set-email-first-name-and-last-name",
                ],
            ],
        "Case 8: Create Customer with Main Customer and Set Email and Username": [
            [5, "case-8-create-customer-with-main-customer-and-set-email-and-username"],
        ],
        "Case 9: Main Case for Backend Boolean Field \u2018Allow Partner Without Email\u2019 at Advance Configuration Tab":
            [
                [
                    5,
                    "case-9-main-case-for-backend-boolean-field-allow-partner-without-email-at-advance-configuration-tab",
                ],
            ],
        "Product Attributes": [[7, "product-attributes"]],
        "The \u201cIMPORT PRODUCT ATTRIBUTES\u201d Button": [
            [7, "the-import-product-attributes-button"],
        ],
        Installation: [[2, "installation"]],
        Prerequisites: [[2, "prerequisites"]],
        "Installation Steps": [[2, "installation-steps"]],
        Introduction: [[3, "introduction"]],
        "About Odoo Woocommerce Connector": [[3, "about-odoo-woocommerce-connector"]],
        "Key Features": [[3, "key-features"]],
        "Getting Started": [[3, "getting-started"]],
        "Product Categories": [[8, "product-categories"]],
        "The \u201cIMPORT PRODUCT CATEGORIES\u201d Button": [
            [8, "the-import-product-categories-button"],
        ],
        "Linking Existing and Imported Categories": [
            [8, "linking-existing-and-imported-categories"],
        ],
        "Product Tags": [[9, "product-tags"]],
        "The \u201cIMPORT PRODUCT TAGS\u201d Button": [
            [9, "the-import-product-tags-button"],
        ],
        "Welcome to Odoo Woocommerce Connector\u2019s documentation!": [
            [1, "welcome-to-odoo-woocommerce-connector-s-documentation"],
        ],
        Product: [[6, "product"]],
        "Advance Configurations of Product": [[6, "advance-configurations-of-product"]],
        "The \u201cIMPORT PRODUCTS\u201d Button": [[6, "the-import-products-button"]],
    },
    indexentries: {},
});
